### PR TITLE
fix issue 103

### LINKED ISSUE #103: Handle tsconfig.json `verbatimModuleSyntax` errors
When using `"verbatimModuleSyntax": true` in `tsconfig.json` I get 74 errors using your amazing package.

All like this one:

```
Error: 'Genders' is a type and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.
import Omocodes from "./enums/omocodes.enum";
import Genders from "./types/genders.type";
```

I think the solution is to change imports like this:

```
import Genders from "./types/genders.type";
```

to this:

```
import type Genders from "./types/genders.type";
```

Am I right?

### PR DESCRIPTION
**Pull request by carmelone**
Fixes https://github.com/Marketto/codice-fiscale-utils/issues/103.

### CODE REVIEW

**Comment by carmelone** [comment]
@Marketto, do you think it's possible to merge and release this ASAP?

**Comment by carmelone** [comment]
@Marketto, do you think it's possible to merge and release this ASAP?

**Comment by carmelone** [comment]
@Marketto, what's the problem that doesn't make you merge this?

**Comment by Marketto** [comment]
Those changes break the unit tests and make the lib not backward compatible with non-verbatim projects.
**A verbatim project doesn't need verbatim dependencies**

Using **_VermatimModuleSyntax_** you just need to import as follows
````typescript
import * as CodiceFiscaleUtils from '@marketto/codice-fiscale-utils';
import type {BelfiorePlace, DateDay, DateMonth, Genders, MultiFormatDate} from '@marketto/codice-fiscale-utils';
````
**No Changes are needed to the source code**
I will add this import hint in the README.MD

**Pull request closed without merging**
